# 你的博客分支名，通常是 main 或 master
main:
  push:
    - stages:
        - name: 安装依赖并构建 # 第一阶段：构建
          image: node:20
          script:
            - npm install
            - npm run build
        - name: 部署到腾讯云 COS # 第二阶段：部署
          image: tencentcom/coscli
          imports: https://cnb.cool/kun_kk/blog_secrets/-/blob/main/tencent.yml
          commands: |
            coscli config set --secret_id $COS_SECRET_ID --secret_key $COS_SECRET_KEY
            coscli config add --init-skip=true -b $COS_BUCKET -r $COS_REGION
            coscli cp ./public cos://$COS_BUCKET -r
